import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  en: { assistantFilled: 'I have filled out:', pleaseReview: 'Please review the form.', sayEmail: 'Please say your email address now.', sayPassword: 'Please say your password.',   networkError: 'Network error. Speech recognition requires an internet connection.',  unsupportedBrowser: 'Speech recognition is not supported in this browser. Please use Google Chrome.',  empty: 'Empty', fieldIsEmpty: 'Field is empty', currentValueIs: 'Current value is',  isCurrentlySetTo: 'is currently set to',  micError: 'Microphone access denied. Please click the lock icon to allow microphone.', 
    appName: "Rythu Sethu",
    tagline: "Bridging Farmers & Customers",
    login: "Login",
    register: "Register",
    logout: "Logout",
    email: "Email Address",
    password: "Password",
    name: "Full Name",
    phone: "Phone Number",
    role: "I am a",
    farmer: "Farmer",
    customer: "Customer",
    agent: "Delivery Agent",
    marketplace: "Marketplace",
    dashboard: "Dashboard",
    addCrop: "Add Crop",
    cropName: "Crop Name",
    price: "Price (₹)",
    quantity: "Quantity",
    location: "Location",
    autoLocation: "Auto-detect Location",
    submit: "Submit",
    loading: "Loading...",
    success: "Success!",
    error: "Error",
    orders: "Orders",
    deliveries: "Deliveries",
    adminPanel: "Admin Panel",
    welcome: "Welcome",
    noData: "No data found",
    search: "Search...",
    cropSuggest: "Crop Suggestions",
    nutritionInfo: "Nutrition Info",
    demandForecast: "Demand Forecast",
    farmerTips: "Farming Tips",
    farmName: "Farm Name",
    farmSize: "Farm Size (acres)",
    soilType: "Soil Type",
    experience: "Experience (years)",
    address: "Delivery Address",
    buy: "Buy Now",
    outOfStock: "Out of Stock",
    status: "Status",
    temperature: "Temperature (°C)",
    humidity: "Humidity (%)",
    rainfall: "Rainfall (mm)",
    analyze: "Analyze",
    languagePref: "Preferred Language",
    aadhaar: "Aadhaar Number (optional)",
    organic: "Organic Product",
    category: "Category",
    description: "Description",
    season: "Season",
    allItems: "All Items",
    veggies: "Veggies",
    fruits: "Fruits",
    grains: "Grains",
    adminVerify: "Admin Verify",
    agentHub: "Agent Hub",
    outForDelivery: "Out for Delivery",
    getStarted: "Get Started Free",
    shopNow: "Shop Now",
    isPrebooking: "Available for Pre-booking",
    harvestDate: "Expected Harvest Date",
    preBook: "Pre-book",
    preBooked: "Pre-booked",
    rewardPoints: "Reward Points",
    experiencePoints: "Experience Points",
    usePoints: "Use Points for Discount",

    home: 'Home',
    seasonalSpecials: 'Seasonal Specials',
    freshlyHarvested: 'Freshly harvested this season!',
    list: 'List',
    map: 'Map',
    placeOrder: 'Place Order',
    deliveryOption: 'Delivery Option',
    buyAtFarm: 'Buy at Farm',
    homeDelivery: 'Home Delivery',
    paymentMethod: 'Payment Method',
    cashOnDelivery: 'Cash on Delivery',
    payOnline: 'Pay Online',
    apply: 'Apply',
    billPreview: 'Bill Preview',
    total: 'Total',
    fetchWeather: 'Fetch Live Weather',
    detecting: 'Detecting...',
    weatherData: 'Weather Data',
    demandForecaster: 'Demand Forecaster',
    predictDemand: 'Predict Demand',
    analyzing: 'Analyzing...',
    smartRoute: 'Smart Route Optimize',
    optimizing: 'Optimizing...',
    routeGenerated: 'Smart Route Generated',
    totalDistance: 'Total Distance',
    notifications: 'Notifications',
    unread: 'Unread',
    noNotifications: 'No new notifications',
    myOrders: 'My Orders',
    cancel: 'Cancel',
    confirm: 'Confirm',
    printBill: 'Print Bill',

    theVision: "The Vision",
    farmersBridge: "The Farmer's Bridge",
    visionDesc: "Just as the ancient Ram Setu was built stone by stone to connect two lands, Rythu Sethu is built block by block—technology, logistics, and trust—to bridge the gap between hard-working farmers and conscious consumers.",
    forFarmers: "For the Farmers",
    growMoreEarnMore: "Grow More. Earn More.",
    farmerDesc: "We eliminate middlemen to ensure that the people who grow our food get the respect and price they deserve. By leveraging AI, we help farmers forecast demand and grow what sells.",
    predictiveAI: "Predictive AI",
    predictiveAIDesc: "Know exactly what to plant for the upcoming season to maximize profits.",
    directAccess: "Direct Access",
    directAccessDesc: "Sell directly to households, restaurants, and local businesses.",
    fairPricing: "Fair Pricing",
    fairPricingDesc: "Set your own prices and keep 100% of the profits.",
    forCustomers: "For the Customers",
    freshHealthy: "Fresh, Healthy, Affordable.",
    customerDesc: "Bring the farm directly to your dining table. By buying straight from the source, you ensure your family gets the freshest organic produce while supporting local agriculture.",
    harvestedToday: "Harvested Today",
    harvestedTodayDesc: "Get vegetables and fruits picked just hours before delivery.",
    lowerPrices: "Lower Prices",
    lowerPricesDesc: "Without middlemen margins, fresh food becomes affordable for everyone.",
    fullTransparency: "Full Transparency",
    fullTransparencyDesc: "Know exactly who grew your food and the soil it came from.",
    theConnection: "The Connection",
    symbioticRel: "A Symbiotic Relationship.",
    connectionDesc: "Rythu Sethu isn't just an app; it's a movement to bring back the lost connection between the grower and the consumer. We build trust, sustainability, and community.",
    smartLogistics: "Smart Logistics",
    smartLogisticsDesc: "Our local delivery agents ensure fast, eco-friendly transport.",
    sustainableFuture: "Sustainable Future",
    sustainableFutureDesc: "Less transportation waste, better soil health, happier families.",
    chooseRole: "Choose Your Role",
    customerPortalDesc: "Browse fresh produce, track orders, get nutritional info",
    farmerPortalDesc: "List crops, get AI suggestions, manage inventory",
    agentPortalDesc: "Manage deliveries, update status, view routes",
    adminPortalDesc: "Oversee the entire platform, users & analytics",
    whyRythuSethu: "Why Rythu Sethu?",
    aiCropSuggest: "AI Crop Suggestions",
    aiCropSuggestDesc: "ML-powered recommendations based on weather & soil",
    liveMapTracking: "Live Map Tracking",
    liveMapTrackingDesc: "See farm locations & track your delivery in real-time",
    voiceInput: "Voice Input",
    voiceInputDesc: "Speak in Telugu, Hindi or English — we understand you",
    demandForecastDescLanding: "Know which crops will sell best this season",
    organicCertified: "Organic Certified",
    organicCertifiedDesc: "Verified organic produce from trusted farmers",
    instantPayments: "Instant Payments",
    instantPaymentsDesc: "UPI, card, and COD — pay the way you prefer",
  },
  te: { assistantFilled: 'I have filled out:', pleaseReview: 'Please review the form.', sayEmail: 'Please say your email address now.', sayPassword: 'Please say your password.',   networkError: 'Network error. Speech recognition requires an internet connection.',  unsupportedBrowser: 'Speech recognition is not supported in this browser. Please use Google Chrome.',  empty: 'Empty', fieldIsEmpty: 'Field is empty', currentValueIs: 'Current value is',  isCurrentlySetTo: 'is currently set to',  micError: 'Microphone access denied. Please click the lock icon to allow microphone.', 
    appName: "Rythu Sethu",
    tagline: "రైతులు & వినియోగదారులను కలుపుతోంది",
    login: "లాగిన్",
    register: "నమోదు",
    logout: "లాగ్అవుట్",
    email: "ఇమెయిల్ చిరునామా",
    password: "పాస్వర్డ్",
    name: "పూర్తి పేరు",
    phone: "ఫోన్ నంబర్",
    role: "నేను ఒక",
    farmer: "రైతు",
    customer: "వినియోగదారుడు",
    agent: "డెలివరీ ఏజెంట్",
    marketplace: "మార్కెట్‌ప్లేస్",
    dashboard: "డాష్‌బోర్డ్",
    addCrop: "పంటను జోడించు",
    cropName: "పంట పేరు",
    price: "ధర (₹)",
    quantity: "పరిమాణం",
    location: "స్థానం",
    autoLocation: "స్వీయ స్థానం",
    submit: "సమర్పించు",
    loading: "లోడవుతోంది...",
    success: "విజయం!",
    error: "లోపం",
    orders: "ఆర్డర్లు",
    deliveries: "డెలివరీలు",
    adminPanel: "అడ్మిన్ ప్యానెల్",
    welcome: "స్వాగతం",
    noData: "డేటా లేదు",
    search: "వెతకండి...",
    cropSuggest: "పంట సూచనలు",
    nutritionInfo: "పోషకాహార సమాచారం",
    demandForecast: "డిమాండ్ అంచనా",
    farmerTips: "వ్యవసాయ చిట్కాలు",
    farmName: "పొలం పేరు",
    farmSize: "పొలం పరిమాణం (ఎకరాలు)",
    soilType: "నేల రకం",
    experience: "అనుభవం (సంవత్సరాలు)",
    address: "డెలివరీ చిరునామా",
    buy: "కొనుగోలు చేయి",
    outOfStock: "స్టాక్ లేదు",
    status: "స్థితి",
    temperature: "ఉష్ణోగ్రత (°C)",
    humidity: "తేమ (%)",
    rainfall: "వర్షపాతం (mm)",
    analyze: "విశ్లేషించు",
    languagePref: "భాష ప్రాధాన్యత",
    aadhaar: "ఆధార్ నంబర్ (ఐచ్ఛికం)",
    organic: "సేంద్రీయ ఉత్పత్తి",
    category: "వర్గం",
    description: "వివరణ",
    season: "సీజన్",
    allItems: "అన్ని వస్తువులు",
    veggies: "కూరగాయలు",
    fruits: "పండ్లు",
    grains: "ధాన్యాలు",
    adminVerify: "అడ్మిన్ ధృవీకరణ",
    agentHub: "ఏజెంట్ హబ్",
    outForDelivery: "డెలివరీ కోసం",
    getStarted: "ఉచితంగా ప్రారంభించండి",
    shopNow: "ఇప్పుడే కొనండి",
    isPrebooking: "ప్రీ-బుకింగ్ కోసం అందుబాటులో ఉంది",
    harvestDate: "ఆశించిన కోత తేదీ",
    preBook: "ముందుగా బుక్ చేయండి",
    preBooked: "ముందుగా బుక్ చేయబడింది",
    rewardPoints: "రివార్డ్ పాయింట్లు",
    experiencePoints: "అనుభవ పాయింట్లు",
    usePoints: "డిస్కౌంట్ కోసం పాయింట్లను ఉపయోగించండి",

    home: 'హోమ్',
    seasonalSpecials: 'సీజనల్ స్పెషల్స్',
    freshlyHarvested: 'ఈ సీజన్‌లో తాజాగా పండించినవి!',
    list: 'జాబితా',
    map: 'మ్యాప్',
    placeOrder: 'ఆర్డర్ చేయండి',
    deliveryOption: 'డెలివరీ ఎంపిక',
    buyAtFarm: 'పొలంలో కొనండి',
    homeDelivery: 'హోమ్ డెలివరీ',
    paymentMethod: 'చెల్లింపు పద్ధతి',
    cashOnDelivery: 'క్యాష్ ఆన్ డెలివరీ',
    payOnline: 'ఆన్‌లైన్ చెల్లింపు',
    apply: 'వర్తించు',
    billPreview: 'బిల్లు ప్రివ్యూ',
    total: 'మొత్తం',
    fetchWeather: 'వాతావరణం పొందండి',
    detecting: 'గుర్తిస్తోంది...',
    weatherData: 'వాతావరణ డేటా',
    demandForecaster: 'డిమాండ్ అంచనా',
    predictDemand: 'డిమాండ్ అంచనా వేయండి',
    analyzing: 'విశ్లేషిస్తోంది...',
    smartRoute: 'స్మార్ట్ రూట్ ఆప్టిమైజ్',
    optimizing: 'ఆప్టిమైజ్ చేస్తోంది...',
    routeGenerated: 'స్మార్ట్ రూట్ రూపొందించబడింది',
    totalDistance: 'మొత్తం దూరం',
    notifications: 'నోటిఫికేషన్‌లు',
    unread: 'చదవనివి',
    noNotifications: 'కొత్త నోటిఫికేషన్‌లు లేవు',
    myOrders: 'నా ఆర్డర్‌లు',
    cancel: 'రద్దు చేయి',
    confirm: 'నిర్ధారించు',
    printBill: 'బిల్లు ప్రింట్ చేయండి',

    theVision: "దృష్టి",
    farmersBridge: "రైతు వారధి",
    visionDesc: "ప్రాచీన రామసేతువును రాతితో నిర్మించినట్లుగా, రైతు సేతువును సాంకేతికత, లాజిస్టిక్స్ మరియు నమ్మకంతో నిర్మించారు.",
    forFarmers: "రైతుల కోసం",
    growMoreEarnMore: "ఎక్కువ పండించండి. ఎక్కువ సంపాదించండి.",
    farmerDesc: "మధ్యవర్తులను తొలగిస్తాము.",
    predictiveAI: "ప్రిడిక్టివ్ AI",
    predictiveAIDesc: "ఏమి పండించాలో తెలుసుకోండి.",
    directAccess: "ప్రత్యక్ష ప్రాప్యత",
    directAccessDesc: "ఇళ్లకు నేరుగా అమ్మండి.",
    fairPricing: "సరసమైన ధర",
    fairPricingDesc: "మీ సొంత ధరలను నిర్ణయించండి.",
    forCustomers: "వినియోగదారుల కోసం",
    freshHealthy: "తాజా, ఆరోగ్యకరమైన, చౌకైన.",
    customerDesc: "పొలాన్ని మీ డైనింగ్ టేబుల్‌కి తీసుకురండి.",
    harvestedToday: "ఈ రోజు పండించినవి",
    harvestedTodayDesc: "డెలివరీకి కొద్ది గంటల ముందు కోసినవి.",
    lowerPrices: "తక్కువ ధరలు",
    lowerPricesDesc: "అందరికీ అందుబాటులో.",
    fullTransparency: "పూర్తి పారదర్శకత",
    fullTransparencyDesc: "మీ ఆహారాన్ని ఎవరు పండించారో తెలుసుకోండి.",
    theConnection: "కనెక్షన్",
    symbioticRel: "సహజీవన సంబంధం.",
    connectionDesc: "రైతు సేతు కేవలం యాప్ కాదు; అదొక ఉద్యమం.",
    smartLogistics: "స్మార్ట్ లాజిస్టిక్స్",
    smartLogisticsDesc: "వేగవంతమైన, పర్యావరణ అనుకూల రవాణా.",
    sustainableFuture: "స్థిరమైన భవిష్యత్తు",
    sustainableFutureDesc: "తక్కువ వ్యర్థాలు, మెరుగైన నేల.",
    chooseRole: "మీ పాత్రను ఎంచుకోండి",
    customerPortalDesc: "తాజా ఉత్పత్తులను బ్రౌజ్ చేయండి",
    farmerPortalDesc: "పంటలను జాబితా చేయండి, AI సూచనలను పొందండి",
    agentPortalDesc: "డెలివరీలను నిర్వహించండి",
    adminPortalDesc: "ప్లాట్‌ఫారమ్‌ను పర్యవేక్షించండి",
    whyRythuSethu: "రైతు సేతు ఎందుకు?",
    aiCropSuggest: "AI పంట సూచనలు",
    aiCropSuggestDesc: "ML-ఆధారిత సిఫార్సులు",
    liveMapTracking: "లైవ్ మ్యాప్ ట్రాకింగ్",
    liveMapTrackingDesc: "మీ డెలివరీని రియల్ టైమ్‌లో ట్రాక్ చేయండి",
    voiceInput: "వాయిస్ ఇన్‌పుట్",
    voiceInputDesc: "స్థానిక భాషలో మాట్లాడండి",
    demandForecastDescLanding: "ఏ పంటలు బాగా అమ్ముడవుతాయో తెలుసుకోండి",
    organicCertified: "ఆర్గానిక్ సర్టిఫైడ్",
    organicCertifiedDesc: "ధృవీకరించబడిన సేంద్రీయ ఉత్పత్తులు",
    instantPayments: "తక్షణ చెల్లింపులు",
    instantPaymentsDesc: "UPI, కార్డ్ మరియు COD",
  },
  hi: { assistantFilled: 'I have filled out:', pleaseReview: 'Please review the form.', sayEmail: 'Please say your email address now.', sayPassword: 'Please say your password.',   networkError: 'Network error. Speech recognition requires an internet connection.',  unsupportedBrowser: 'Speech recognition is not supported in this browser. Please use Google Chrome.',  empty: 'Empty', fieldIsEmpty: 'Field is empty', currentValueIs: 'Current value is',  isCurrentlySetTo: 'is currently set to',  micError: 'Microphone access denied. Please click the lock icon to allow microphone.', 
    appName: "Rythu Sethu",
    tagline: "किसानों और ग्राहकों को जोड़ना",
    login: "लॉगिन",
    register: "पंजीकरण",
    logout: "लॉगआउट",
    email: "ईमेल पता",
    password: "पासवर्ड",
    name: "पूरा नाम",
    phone: "फोन नंबर",
    role: "मैं हूं",
    farmer: "किसान",
    customer: "ग्राहक",
    agent: "डिलीवरी एजेंट",
    marketplace: "बाज़ार",
    dashboard: "डैशबोर्ड",
    addCrop: "फसल जोड़ें",
    cropName: "फसल का नाम",
    price: "कीमत (₹)",
    quantity: "मात्रा",
    location: "स्थान",
    autoLocation: "स्वतः स्थान",
    submit: "जमा करें",
    loading: "लोड हो रहा है...",
    success: "सफलता!",
    error: "त्रुटि",
    orders: "ऑर्डर",
    deliveries: "डिलीवरी",
    adminPanel: "एडमिन पैनल",
    welcome: "स्वागत है",
    noData: "डेटा नहीं मिला",
    search: "खोजें...",
    cropSuggest: "फसल सुझाव",
    nutritionInfo: "पोषण जानकारी",
    demandForecast: "मांग पूर्वानुमान",
    farmerTips: "खेती के सुझाव",
    farmName: "खेत का नाम",
    farmSize: "खेत का आकार (एकड़)",
    soilType: "मिट्टी का प्रकार",
    experience: "अनुभव (वर्ष)",
    address: "डिलीवरी पता",
    buy: "अभी खरीदें",
    outOfStock: "स्टॉक में नहीं",
    status: "स्थिति",
    temperature: "तापमान (°C)",
    humidity: "आर्द्रता (%)",
    rainfall: "वर्षा (mm)",
    analyze: "विश्लेषण करें",
    languagePref: "भाषा प्राथमिकता",
    aadhaar: "आधार नंबर (वैकल्पिक)",
    organic: "जैविक उत्पाद",
    category: "श्रेणी",
    description: "विवरण",
    season: "मौसम",
    allItems: "सभी वस्तुएं",
    veggies: "सब्जियां",
    fruits: "फल",
    grains: "अनाज",
    adminVerify: "व्यवस्थापक सत्यापन",
    agentHub: "एजेंट हब",
    outForDelivery: "डिलीवरी के लिए तैयार",
    getStarted: "मुफ्त में शुरू करें",
    shopNow: "अभी खरीदें",
    isPrebooking: "प्री-बुकिंग के लिए उपलब्ध",
    harvestDate: "फसल कटाई की संभावित तिथि",
    preBook: "प्री-बुक",
    preBooked: "प्री-बुक किया गया",
    rewardPoints: "इनाम अंक",
    experiencePoints: "अनुभव अंक",
    usePoints: "छूट के लिए अंकों का उपयोग करें",

    home: 'होम',
    seasonalSpecials: 'मौसमी विशेष',
    freshlyHarvested: 'इस मौसम में ताज़ा काटा गया!',
    list: 'सूची',
    map: 'नक्शा',
    placeOrder: 'ऑर्डर करें',
    deliveryOption: 'डिलीवरी विकल्प',
    buyAtFarm: 'खेत पर खरीदें',
    homeDelivery: 'होम डिलीवरी',
    paymentMethod: 'भुगतान विधि',
    cashOnDelivery: 'कैश ऑन डिलीवरी',
    payOnline: 'ऑनलाइन भुगतान करें',
    apply: 'लागू करें',
    billPreview: 'बिल पूर्वावलोकन',
    total: 'कुल',
    fetchWeather: 'मौसम की जानकारी लाएं',
    detecting: 'पता लगा रहा है...',
    weatherData: 'मौसम डेटा',
    demandForecaster: 'मांग पूर्वानुमानकर्ता',
    predictDemand: 'मांग का अनुमान लगाएं',
    analyzing: 'विश्लेषण कर रहा है...',
    smartRoute: 'स्मार्ट मार्ग अनुकूलित करें',
    optimizing: 'अनुकूलित कर रहा है...',
    routeGenerated: 'स्मार्ट मार्ग उत्पन्न',
    totalDistance: 'कुल दूरी',
    notifications: 'सूचनाएं',
    unread: 'अपठित',
    noNotifications: 'कोई नई सूचना नहीं',
    myOrders: 'मेरे ऑर्डर',
    cancel: 'रद्द करें',
    confirm: 'पुष्टि करें',
    printBill: 'बिल प्रिंट करें',

    theVision: "दृष्टिकोण",
    farmersBridge: "किसान का पुल",
    visionDesc: "जैसे प्राचीन राम सेतु को दो भूमियों को जोड़ने के लिए पत्थर-दर-पत्थर बनाया गया था, वैसे ही रैतु सेतु को तकनीक, रसद और विश्वास से बनाया गया है।",
    forFarmers: "किसानों के लिए",
    growMoreEarnMore: "अधिक उगाएं। अधिक कमाएं।",
    farmerDesc: "हम बिचौलियों को खत्म करते हैं।",
    predictiveAI: "अनुमानित AI",
    predictiveAIDesc: "जानें कि क्या रोपना है।",
    directAccess: "सीधी पहुँच",
    directAccessDesc: "सीधे घरों में बेचें।",
    fairPricing: "उचित मूल्य",
    fairPricingDesc: "अपनी खुद की कीमतें तय करें।",
    forCustomers: "ग्राहकों के लिए",
    freshHealthy: "ताजा, स्वस्थ, किफायती।",
    customerDesc: "खेत को सीधे अपने डाइनिंग टेबल पर लाएं।",
    harvestedToday: "आज कटा हुआ",
    harvestedTodayDesc: "डिलीवरी से कुछ घंटे पहले चुना गया।",
    lowerPrices: "कम कीमतें",
    lowerPricesDesc: "सभी के लिए किफायती।",
    fullTransparency: "पूर्ण पारदर्शिता",
    fullTransparencyDesc: "जानें कि आपका भोजन किसने उगाया है।",
    theConnection: "कनेक्शन",
    symbioticRel: "एक सहजीवी संबंध।",
    connectionDesc: "रैतु सेतु सिर्फ एक ऐप नहीं है; यह एक आंदोलन है।",
    smartLogistics: "स्मार्ट रसद",
    smartLogisticsDesc: "तेज, पर्यावरण के अनुकूल परिवहन।",
    sustainableFuture: "टिकाऊ भविष्य",
    sustainableFutureDesc: "कम अपशिष्ट, बेहतर मिट्टी।",
    chooseRole: "अपनी भूमिका चुनें",
    customerPortalDesc: "ताजा उपज ब्राउज़ करें",
    farmerPortalDesc: "फसलें सूचीबद्ध करें, AI सुझाव प्राप्त करें",
    agentPortalDesc: "डिलीवरी प्रबंधित करें",
    adminPortalDesc: "मंच की निगरानी करें",
    whyRythuSethu: "रैतु सेतु क्यों?",
    aiCropSuggest: "AI फसल सुझाव",
    aiCropSuggestDesc: "एमएल-संचालित सिफारिशें",
    liveMapTracking: "लाइव मैप ट्रैकिंग",
    liveMapTrackingDesc: "रीयल-टाइम में अपनी डिलीवरी ट्रैक करें",
    voiceInput: "आवाज इनपुट",
    voiceInputDesc: "स्थानीय भाषा में बात करें",
    demandForecastDescLanding: "जानें कि कौन सी फसलें सबसे अच्छी बिकेंगी",
    organicCertified: "जैविक प्रमाणित",
    organicCertifiedDesc: "सत्यापित जैविक उपज",
    instantPayments: "त्वरित भुगतान",
    instantPaymentsDesc: "यूपीआई, कार्ड और सीओडी",
  },
  kn: { assistantFilled: 'I have filled out:', pleaseReview: 'Please review the form.', sayEmail: 'Please say your email address now.', sayPassword: 'Please say your password.',   networkError: 'Network error. Speech recognition requires an internet connection.',  unsupportedBrowser: 'Speech recognition is not supported in this browser. Please use Google Chrome.',  empty: 'Empty', fieldIsEmpty: 'Field is empty', currentValueIs: 'Current value is',  isCurrentlySetTo: 'is currently set to',  micError: 'Microphone access denied. Please click the lock icon to allow microphone.', 
    appName: "Rythu Sethu",
    tagline: "ರೈತರು ಮತ್ತು ಗ್ರಾಹಕರನ್ನು ಜೋಡಿಸುವುದು",
    login: "ಲಾಗಿನ್",
    register: "ನೋಂದಣಿ",
    logout: "ಲಾಗ್ ಔಟ್",
    email: "ಇಮೇಲ್ ವಿಳಾಸ",
    password: "ಪಾಸ್ವರ್ಡ್",
    name: "ಪೂರ್ಣ ಹೆಸರು",
    phone: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    role: "ನಾನು",
    farmer: "ರೈತ",
    customer: "ಗ್ರಾಹಕ",
    agent: "ಡೆಲಿವರಿ ಏಜೆಂಟ್",
    marketplace: "ಮಾರುಕಟ್ಟೆ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    addCrop: "ಬೆಳೆ ಸೇರಿಸಿ",
    cropName: "ಬೆಳೆ ಹೆಸರು",
    price: "ಬೆಲೆ (₹)",
    quantity: "ಪ್ರಮಾಣ",
    location: "ಸ್ಥಳ",
    autoLocation: "ಸ್ವಯಂ ಸ್ಥಳ ಪತ್ತೆ",
    submit: "ಸಲ್ಲಿಸು",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    success: "ಯಶಸ್ಸು!",
    error: "ದೋಷ",
    orders: "ಆರ್ಡರ್‌ಗಳು",
    deliveries: "ಡೆಲಿವರಿಗಳು",
    adminPanel: "ನಿರ್ವಾಹಕ ಫಲಕ",
    welcome: "ಸ್ವಾಗತ",
    noData: "ಮಾಹಿತಿ ಇಲ್ಲ",
    search: "ಹುಡುಕಿ...",
    cropSuggest: "ಬೆಳೆ ಸಲಹೆಗಳು",
    nutritionInfo: "ಪೌಷ್ಟಿಕಾಂಶ ಮಾಹಿತಿ",
    demandForecast: "ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆ",
    farmerTips: "ವ್ಯವಸಾಯ ಸಲಹೆಗಳು",
    farmName: "ಹೊಲದ ಹೆಸರು",
    farmSize: "ಹೊಲದ ಗಾತ್ರ (ಎಕರೆ)",
    soilType: "ಮಣ್ಣಿನ ವಿಧ",
    experience: "ಅನ್ಯುಭವ (ವರ್ಷಗಳು)",
    address: "ವಿತರಣಾ ವಿಳಾಸ",
    buy: "ಖರೀದಿಸಿ",
    outOfStock: "ದಾಸ್ತಾನು ಇಲ್ಲ",
    status: "ಸ್ಥಿತಿ",
    temperature: "ತಾಪಮಾನ (°C)",
    humidity: "ಆರ್ದ್ರತೆ (%)",
    rainfall: "ಮಳೆ ಪ್ರಮಾಣ (mm)",
    analyze: "ವಿಶ್ಲೇಷಿಸು",
    languagePref: "ಆದ್ಯತೆಯ ಭಾಷೆ",
    aadhaar: "ಆಧಾರ್ ಸಂಖ್ಯೆ (ಐಚ್ಛಿಕ)",
    organic: "ಸಾವಯವ ಉತ್ಪನ್ನ",
    category: "ವರ್ಗ",
    description: "ವಿವರಣೆ",
    season: "ಋತು",
    allItems: "ಎಲ್ಲಾ ವಸ್ತುಗಳು",
    veggies: "ತರಕಾರಿಗಳು",
    fruits: "ಹಣ್ಣುಗಳು",
    grains: "ಧಾನ್ಯಗಳು",
    adminVerify: "ನಿರ್ವಾಹಕರ ಪರಿಶೀಲನೆ",
    agentHub: "ಏಜೆಂಟ್ ಹಬ್",
    outForDelivery: "ವಿತರಣೆಗೆ ಸಿದ್ಧ",
    getStarted: "ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ",
    shopNow: "ಈಗ ಖರೀದಿಸಿ",
    isPrebooking: "ಪ್ರೀ-ಬುಕಿಂಗ್‌ಗೆ ಲಭ್ಯವಿದೆ",
    harvestDate: "ನಿರೀಕ್ಷಿತ ಕಟಾವು ದಿನಾಂಕ",
    preBook: "ಪ್ರೀ-ಬುಕ್",
    preBooked: "ಪ್ರೀ-ಬುಕ್ ಮಾಡಲಾಗಿದೆ",
    rewardPoints: "ರಿವಾರ್ಡ್ ಪಾಯಿಂಟ್‌ಗಳು",
    experiencePoints: "ಅನುಭವ ಪಾಯಿಂಟ್‌ಗಳು",
    usePoints: "ರಿಯಾಯಿತಿಗಾಗಿ ಪಾಯಿಂಟ್‌ಗಳನ್ನು ಬಳಸಿ",

    home: 'ಮುಖಪುಟ',
    seasonalSpecials: 'ಋತುಮಾನದ ವಿಶೇಷತೆಗಳು',
    freshlyHarvested: 'ಈ ಋತುವಿನಲ್ಲಿ ತಾಜಾವಾಗಿ ಕಟಾವು ಮಾಡಲಾಗಿದೆ!',
    list: 'ಪಟ್ಟಿ',
    map: 'ನಕ್ಷೆ',
    placeOrder: 'ಆರ್ಡರ್ ಮಾಡಿ',
    deliveryOption: 'ವಿತರಣೆ ಆಯ್ಕೆ',
    buyAtFarm: 'ಹೊಲದಲ್ಲಿ ಖರೀದಿಸಿ',
    homeDelivery: 'ಮನೆ ವಿತರಣೆ',
    paymentMethod: 'ಪಾವತಿ ವಿಧಾನ',
    cashOnDelivery: 'ವಿತರಣೆಯ ನಂತರ ನಗದು',
    payOnline: 'ಆನ್‌ಲೈನ್ ಪಾವತಿಸಿ',
    apply: 'ಅನ್ವಯಿಸು',
    billPreview: 'ಬಿಲ್ ಮುನ್ನೋಟ',
    total: 'ಒಟ್ಟು',
    fetchWeather: 'ಹವಾಮಾನ ಮಾಹಿತಿ ಪಡೆಯಿರಿ',
    detecting: 'ಪತ್ತೆಹಚ್ಚಲಾಗುತ್ತಿದೆ...',
    weatherData: 'ಹವಾಮಾನ ಡೇಟಾ',
    demandForecaster: 'ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆಕಾರ',
    predictDemand: 'ಬೇಡಿಕೆಯನ್ನು ಅಂದಾಜು ಮಾಡಿ',
    analyzing: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    smartRoute: 'ಸ್ಮಾರ್ಟ್ ಮಾರ್ಗ ಆಪ್ಟಿಮೈಸ್',
    optimizing: 'ಆಪ್ಟಿಮೈಸ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    routeGenerated: 'ಸ್ಮಾರ್ಟ್ ಮಾರ್ಗ ರಚಿಸಲಾಗಿದೆ',
    totalDistance: 'ಒಟ್ಟು ದೂರ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    unread: 'ಓದದಿರುವ',
    noNotifications: 'ಯಾವುದೇ ಹೊಸ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',
    myOrders: 'ನನ್ನ ಆರ್ಡರ್‌ಗಳು',
    cancel: 'ರದ್ದುಮಾಡು',
    confirm: 'ಖಚಿತಪಡಿಸಿ',
    printBill: 'ಬಿಲ್ ಮುದ್ರಿಸಿ',

    theVision: "ದೃಷ್ಟಿಕೋನ",
    farmersBridge: "ರೈತರ ಸೇತುವೆ",
    visionDesc: "ಪ್ರಾಚೀನ ರಾಮ ಸೇತುವೆಯಂತೆ, ರೈತು ಸೇತುವನ್ನು ತಂತ್ರಜ್ಞಾನ, ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಮತ್ತು ನಂಬಿಕೆಯಿಂದ ನಿರ್ಮಿಸಲಾಗಿದೆ.",
    forFarmers: "ರೈತರಿಗಾಗಿ",
    growMoreEarnMore: "ಹೆಚ್ಚು ಬೆಳೆಯಿರಿ. ಹೆಚ್ಚು ಗಳಿಸಿ.",
    farmerDesc: "ನಾವು ಮಧ್ಯವರ್ತಿಗಳನ್ನು ತೆಗೆದುಹಾಕುತ್ತೇವೆ.",
    predictiveAI: "ಪೂರ್ವಸೂಚಕ AI",
    predictiveAIDesc: "ಏನು ನೆಡಬೇಕು ಎಂದು ತಿಳಿಯಿರಿ.",
    directAccess: "ನೇರ ಪ್ರವೇಶ",
    directAccessDesc: "ಮನೆಗಳಿಗೆ ನೇರವಾಗಿ ಮಾರಾಟ ಮಾಡಿ.",
    fairPricing: "ನ್ಯಾಯಯುತ ಬೆಲೆ",
    fairPricingDesc: "ನಿಮ್ಮ ಸ್ವಂತ ಬೆಲೆಗಳನ್ನು ನಿಗದಿಪಡಿಸಿ.",
    forCustomers: "ಗ್ರಾಹಕರಿಗಾಗಿ",
    freshHealthy: "ತಾಜಾ, ಆರೋಗ್ಯಕರ, ಕೈಗೆಟಕುವ.",
    customerDesc: "ಹೊಲವನ್ನು ನಿಮ್ಮ ಡೈನಿಂಗ್ ಟೇಬಲ್‌ಗೆ ತರಲು.",
    harvestedToday: "ಇಂದು ಕಟಾವು ಮಾಡಿದ",
    harvestedTodayDesc: "ವಿತರಣೆಗೆ ಕೆಲವೇ ಗಂಟೆಗಳ ಮೊದಲು ಆರಿಸಲಾಗಿದೆ.",
    lowerPrices: "ಕಡಿಮೆ ಬೆಲೆಗಳು",
    lowerPricesDesc: "ಎಲ್ಲರಿಗೂ ಕೈಗೆಟಕುವಂತಿದೆ.",
    fullTransparency: "ಸಂಪೂರ್ಣ ಪಾರದರ್ಶಕತೆ",
    fullTransparencyDesc: "ನಿಮ್ಮ ಆಹಾರವನ್ನು ಯಾರು ಬೆಳೆದಿದ್ದಾರೆಂದು ತಿಳಿಯಿರಿ.",
    theConnection: "ಸಂಪರ್ಕ",
    symbioticRel: "ಸಹಜೀವನದ ಸಂಬಂಧ.",
    connectionDesc: "ರೈತು ಸೇತು ಕೇವಲ ಅಪ್ಲಿಕೇಶನ್ ಅಲ್ಲ; ಅದೊಂದು ಚಳುವಳಿ.",
    smartLogistics: "ಸ್ಮಾರ್ಟ್ ಲಾಜಿಸ್ಟಿక్స్",
    smartLogisticsDesc: "ವೇಗದ, ಪರಿಸರ ಸ್ನೇಹಿ ಸಾರಿಗೆ.",
    sustainableFuture: "ಸುಸ್ಥಿರ ಭವಿಷ್ಯ",
    sustainableFutureDesc: "ಕಡಿಮೆ ತ್ಯಾಜ್ಯ, ಉತ್ತಮ ಮಣ್ಣು.",
    chooseRole: "ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆರಿಸಿ",
    customerPortalDesc: "ತಾಜಾ ಉತ್ಪನ್ನಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ",
    farmerPortalDesc: "ಬೆಳೆಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿ, AI ಸಲಹೆಗಳನ್ನು ಪಡೆಯಿರಿ",
    agentPortalDesc: "ವಿತರಣೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    adminPortalDesc: "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಅನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ",
    whyRythuSethu: "ರೈತು ಸೇತು ಏಕೆ?",
    aiCropSuggest: "AI ಬೆಳೆ ಸಲಹೆಗಳು",
    aiCropSuggestDesc: "ಎಂಎಲ್-ಚಾಲಿತ ಶಿಫಾರಸುಗಳು",
    liveMapTracking: "ಲೈವ್ ಮ್ಯಾಪ್ ಟ್ರ್ಯಾಕಿಂಗ್",
    liveMapTrackingDesc: "ನಿಮ್ಮ ವಿತರಣೆಯನ್ನು ನೈಜ ಸಮಯದಲ್ಲಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    voiceInput: "ಧ್ವನಿ ಇನ್ಪುಟ್",
    voiceInputDesc: "ಸ್ಥಳೀಯ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ",
    demandForecastDescLanding: "ಯಾವ ಬೆಳೆಗಳು ಉತ್ತಮವಾಗಿ ಮಾರಾಟವಾಗುತ್ತವೆ ಎಂಬುದನ್ನು ತಿಳಿಯಿರಿ",
    organicCertified: "ಸಾವಯವ ಪ್ರಮಾಣೀಕೃತ",
    organicCertifiedDesc: "ಪರಿಶೀಲಿಸಿದ ಸಾವಯವ ಉತ್ಪನ್ನ",
    instantPayments: "ತ್ವರಿತ ಪಾವತಿಗಳು",
    instantPaymentsDesc: "ಯುಪಿಐ, कार्ड और सीओडी",
  },
  ta: { assistantFilled: 'I have filled out:', pleaseReview: 'Please review the form.', sayEmail: 'Please say your email address now.', sayPassword: 'Please say your password.',   networkError: 'Network error. Speech recognition requires an internet connection.',  unsupportedBrowser: 'Speech recognition is not supported in this browser. Please use Google Chrome.',  empty: 'Empty', fieldIsEmpty: 'Field is empty', currentValueIs: 'Current value is',  isCurrentlySetTo: 'is currently set to',  micError: 'Microphone access denied. Please click the lock icon to allow microphone.', 
    appName: "Rythu Sethu",
    tagline: "விவசாயிகளையும் வாடிக்கையாளர்களையும் இணைக்கிறது",
    login: "உள்நுழை",
    register: "பதிவு செய்",
    logout: "வெளியேறு",
    email: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    name: "முழு பெயர்",
    phone: "தொலைபேசி எண்",
    role: "நான் ஒரு",
    farmer: "விவசாயி",
    customer: "வாடிக்கையாளர்",
    agent: "டெலிவரி முகவர்",
    marketplace: "சந்தை",
    dashboard: "டாஷ்போர்டு",
    addCrop: "பயிரைச் சேர்",
    cropName: "பயிர் பெயர்",
    price: "விலை (₹)",
    quantity: "அளவு",
    location: "இடம்",
    autoLocation: "தானியங்கி இருப்பிடம்",
    submit: "சமர்ப்பி",
    loading: "ஏற்றப்படுகிறது...",
    success: "வெற்றி!",
    error: "பிழை",
    orders: "ஆர்டர்கள்",
    deliveries: "டெலிவரிகள்",
    adminPanel: "நிர்வாக குழு",
    welcome: "வரவேற்பு",
    noData: "தரவு எதுவும் இல்லை",
    search: "தேடுக...",
    cropSuggest: "பயிர் ஆலோசனைகள்",
    nutritionInfo: "ஊட்டச்சத்து தகவல்",
    demandForecast: "தேவை கணிப்பு",
    farmerTips: "விவசாய குறிப்புகள்",
    farmName: "பண்ணை பெயர்",
    farmSize: "பண்ணை அளவு (ஏக்கர்)",
    soilType: "மண் வகை",
    experience: "அனுபவம் (ஆண்டுகள்)",
    address: "டெலிவரி முகவரி",
    buy: "இப்போதே வாங்கு",
    outOfStock: "இருப்பு இல்லை",
    status: "நிலை",
    temperature: "வெப்பநிலை (°C)",
    humidity: "ஈரப்பதம் (%)",
    rainfall: "மழைப்பொழிவு (mm)",
    analyze: "பகுப்பாய்வு செய்",
    languagePref: "விருப்பமான மொழி",
    aadhaar: "ஆதார் எண் (விருப்பத்தேர்வு)",
    organic: "இயற்கை தயாரிப்பு",
    category: "வகை",
    description: "விளக்கம்",
    season: "பருவம்",
    allItems: "அனைத்து பொருட்கள்",
    veggies: "காய்கறிகள்",
    fruits: "பழங்கள்",
    grains: "தானியங்கள்",
    adminVerify: "நிர்வாகி சரிபார்ப்பு",
    agentHub: "முகவர் மையம்",
    outForDelivery: "டெலிவரிக்கு தயாராக உள்ளது",
    getStarted: "இலவசமாக தொடங்குங்கள்",
    shopNow: "இப்போதே வாங்கவும்",
    isPrebooking: "முன்பதிவுக்கு கிடைக்கிறது",
    harvestDate: "எதிர்பார்க்கப்படும் அறுவடை தேதி",
    preBook: "முன்பதிவு",
    preBooked: "முன்பதிவு செய்யப்பட்டது",
    rewardPoints: "வெகுமதி புள்ளிகள்",
    experiencePoints: "அனுபவ புள்ளிகள்",
    usePoints: "தள்ளுபடிக்கு புள்ளிகளை பயன்படுத்தவும்",

    home: 'முகப்பு',
    seasonalSpecials: 'பருவகால சிறப்புகள்',
    freshlyHarvested: 'இந்த பருவத்தில் புதிதாக அறுவடை செய்யப்பட்டது!',
    list: 'பட்டியல்',
    map: 'வரைபடம்',
    placeOrder: 'ஆர்டர் செய்',
    deliveryOption: 'டெலிவரி விருப்பம்',
    buyAtFarm: 'பண்ணையில் வாங்குங்கள்',
    homeDelivery: 'ஹோம் டெலிவரி',
    paymentMethod: 'கட்டண முறை',
    cashOnDelivery: 'பணம் செலுத்தி பெறுதல்',
    payOnline: 'ஆன்லைனில் செலுத்துங்கள்',
    apply: 'பயன்படுத்து',
    billPreview: 'ரசீது முன்னோட்டம்',
    total: 'மொத்தம்',
    fetchWeather: 'வானிலை தகவலைப் பெறு',
    detecting: 'கண்டறியப்படுகிறது...',
    weatherData: 'வானிலை தரவு',
    demandForecaster: 'தேவை கணிப்பாளர்',
    predictDemand: 'தேவையை கணிக்கவும்',
    analyzing: 'பகுப்பாய்வு செய்யப்படுகிறது...',
    smartRoute: 'ஸ்மார்ட் வழியை மேம்படுத்து',
    optimizing: 'மேம்படுத்தப்படுகிறது...',
    routeGenerated: 'ஸ்மார்ட் வழி உருவாக்கப்பட்டது',
    totalDistance: 'மொத்த தூரம்',
    notifications: 'அறிவிப்புகள்',
    unread: 'படிக்காதவை',
    noNotifications: 'புதிய அறிவிப்புகள் இல்லை',
    myOrders: 'என் ஆர்டர்கள்',
    cancel: 'ரத்து செய்',
    confirm: 'உறுதிப்படுத்து',
    printBill: 'ரசீதை அச்சிடு',

    theVision: "பார்வை",
    farmersBridge: "விவசாயியின் பாலம்",
    visionDesc: "பழங்கால ராமர் பாலத்தைப் போல, ரைத்து சேது தொழில்நுட்பம், தளவாடங்கள் மற்றும் நம்பிக்கையால் உருவாக்கப்பட்டுள்ளது.",
    forFarmers: "விவசாயிகளுக்காக",
    growMoreEarnMore: "அதிகம் வளருங்கள். அதிகம் சம்பாதியுங்கள்.",
    farmerDesc: "இடைத்தரகர்களை நாங்கள் அகற்றுகிறோம்.",
    predictiveAI: "முன்கணிப்பு AI",
    predictiveAIDesc: "என்ன நட வேண்டும் என்பதை தெரிந்து கொள்ளுங்கள்.",
    directAccess: "நேரடி அணுகல்",
    directAccessDesc: "நேரடியாக வீடுகளுக்கு விற்கவும்.",
    fairPricing: "நியாயமான விலை",
    fairPricingDesc: "உங்கள் சொந்த விலைகளை நிர்ணயிக்கவும்.",
    forCustomers: "வாடிக்கையாளர்களுக்காக",
    freshHealthy: "புதிய, ஆரோக்கியமான, மலிவான.",
    customerDesc: "பண்ணையை உங்கள் சாப்பாட்டு மேசைக்கு கொண்டு வாருங்கள்.",
    harvestedToday: "இன்று அறுவடை செய்யப்பட்டது",
    harvestedTodayDesc: "டெலிவரிக்கு சில மணிநேரங்களுக்கு முன்பு எடுக்கப்பட்டது.",
    lowerPrices: "குறைந்த விலைகள்",
    lowerPricesDesc: "அனைவருக்கும் மலிவானது.",
    fullTransparency: "முழு வெளிப்படைத்தன்மை",
    fullTransparencyDesc: "உங்கள் உணவை யார் வளர்த்தார்கள் என்பதை தெரிந்து கொள்ளுங்கள்.",
    theConnection: "இணைப்பு",
    symbioticRel: "ஒரு கூட்டுறவு உறவு.",
    connectionDesc: "ரைத்து சேது ஒரு பயன்பாடு அல்ல; அது ஒரு இயக்கம்.",
    smartLogistics: "ஸ்மார்ட் லாஜிஸ்டிக்ஸ்",
    smartLogisticsDesc: "வேகமான, சுற்றுச்சூழல் நட்பு போக்குவரத்து.",
    sustainableFuture: "நிலையான எதிர்காலம்",
    sustainableFutureDesc: "குறைந்த கழிவுகள், சிறந்த மண்.",
    chooseRole: "உங்கள் பங்கைத் தேர்வுசெய்க",
    customerPortalDesc: "புதிய பொருட்களை உலாவவும்",
    farmerPortalDesc: "பயிர்களை பட்டியலிடுங்கள், AI ஆலோசனைகளைப் பெறுங்கள்",
    agentPortalDesc: "டெலிவரிகளை நிர்வகிக்கவும்",
    adminPortalDesc: "தளத்தை கண்காணிக்கவும்",
    whyRythuSethu: "ரைத்து சேது ஏன்?",
    aiCropSuggest: "AI பயிர் ஆலோசனைகள்",
    aiCropSuggestDesc: "எம்எல் அடிப்படையிலான பரிந்துரைகள்",
    liveMapTracking: "நேரடி வரைபடக் கண்காணிப்பு",
    liveMapTrackingDesc: "உங்கள் டெலிவரியை நிகழ்நேரத்தில் கண்காணிக்கவும்",
    voiceInput: "குரல் உள்ளீடு",
    voiceInputDesc: "உள்ளூர் மொழியில் பேசுங்கள்",
    demandForecastDescLanding: "எந்தப் பயிர்கள் சிறப்பாக விற்கப்படும் என்பதைத் தெரிந்துகொள்ளுங்கள்",
    organicCertified: "ஆர்கானிக் சான்றிதழ்",
    organicCertifiedDesc: "சரிபார்க்கப்பட்ட ஆர்கானிக் தயாரிப்புகள்",
    instantPayments: "உடனடி பணம் செலுத்துதல்",
    instantPaymentsDesc: "யுபிஐ, அட்டை மற்றும் சிஓடி",
  },
};

const LangContext = createContext();

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "en");

  const changeLang = (l) => {
    setLang(l);
    localStorage.setItem("lang", l);
  };

  useEffect(() => {
    const triggerTranslation = () => {
      try {
        const gtCombo = document.querySelector(".goog-te-combo");
        if (gtCombo) {
          gtCombo.value = lang;
          gtCombo.dispatchEvent(new Event("change", { bubbles: true, cancelable: true }));
          return true;
        }
      } catch (e) {}
      return false;
    };
    
    if (!triggerTranslation()) {
      // If combo box is not yet rendered, try again a few times
      let attempts = 0;
      const interval = setInterval(() => {
        if (triggerTranslation() || attempts > 10) {
          clearInterval(interval);
        }
        attempts++;
      }, 500);
    }
  }, [lang]);

  const t = (key) => translations[lang]?.[key] || translations["en"]?.[key] || key;

  return (
    <LangContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
export { LangContext };
